[phases.setup]
nixPkgs = ["python39", "postgresql", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    ". /opt/venv/bin/activate && python manage.py collectstatic --noinput --clear",
    ". /opt/venv/bin/activate && python manage.py migrate --noinput",
    ". /opt/venv/bin/activate && python manage.py load_sample_data"
]

[phases.start]
cmd = "gunicorn config.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
