[phases.setup]
nixPkgs = ["python39", "postgresql", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn config.wsgi --bind 0.0.0.0:$PORT"
